[WETH]
0x7BA605bC00eA26512a639D5e0335EAEb3e81aD94 = 200323663348
0x3588f30d13d9b783A2C5628350260a9bd85A3CF7 = 205170532
0xBB2d41AcfEA24A3A2aD4A6F95C3AcE1cC98c6ed6 = 3068584682722
0xc572c95996653ae98Ec3A59d9a511eDA142b98C1 = 595158234550
0x87caC3B3e50B69CE2d888eC67214C8e673ECb0E6 = 14622774121
0x434e8971592E898316dc8b7a39D6f9Be03ed5f66 = 12558442
0x2222A442b18Cc3Ff723c996C4FEc9714D964fFc8 = 41857180756940
0x5c16D4266605F799dD04d8443F4090ebF53C30f1 = 446088640665
0xFE0402CD4D5259A7ebb66E1DeEdD5cCA75D8dc78 = 401640559186320
0x9e55f1678560FD2B345ac9A509DF55Bf732632f1 = 2958869
0x3ece8d40daC89FfB408f7CB5eaf24Ab6A3135028 = 169318
0xe67e76380C3cc0E8c6E178b4f683d039F38e24a1 = 12080371646068
0x2bA32158A46EA89F66fC75B14d6C94cDC64b0f33 = 147435107518
0x0e2481cdC9fFD4DA1EE17b3060D41c7A0a4906B7 = 523803266
0x345458f902e9C61Adfc1153eb27E14458B8aE65F = 727696895912
0x12ceE0c966988F2E4e5831f0160c27e0564f8009 = 21304717813573
0x6f54c02199E7474bb4787d9a0d8f41093d397Af0 = 675676902783
0xcE2f0727943E7c1a17f27aA6F67Ed6821cDF8d7D = 3127301636340
0x44D44A37868d027DaBac36e6F92E9F570E9Fd6B2 = 40164055918632
0xA06Dc8C3d4eB77d49Be456C028F5b6d3dc42Fb78 = 45100
0x583233Be2835f24188dfcb911558D70B8Fe5ae46 = 803281118373
0xBD8D232554F426b8817442052AcbAB247Bc63C3B = 3944405060923
0x7B99c763b7B70B05a47Db32E78847c3999F671d9 = 3462038
0x071Ef7f7b9dbabA85Fd6dC9f9a9b10e71F00A69b = 8368152361778
0x91Bf2FF1Aa22ea919850FF41B265Af937E330507 = 395910489695
0xEC75b05A02d0DFaF30391D4FaF58753947b8E000 = 8028760886639
0x2c0d351e5B58722676da689A4C2b7cfe68A6052E = 18531990272165
0x7BDa60f3f7c3009edF8EB8DdCb43c1f92584CcA7 = 5071942604491
0x814055779F8d2F591277b76C724b7AdC74fb82D9 = 10035722189536
0xa4e766870cb00f6f02f36754C0Da8995E0e5BA91 = 4816585654038
0x879585Bc421733F4474EAbecfb01729822D6391d = 12293300
0xaeDC687fa5376d2Fe9D4B81EbFC8C2bA30ba54aE = 1388030229958
0x406B10999Fc1529B2743663d53487C3612874f3E = 6020385992232
0x9ff84B91998dF96A6587DB8dDe8D4E47518107d6 = 1208555288713
0x10cA916e40AC8e36Dd6618ae4Cce1F49685e2e57 = 1564266783994446
0x5C6329c9108ed3a72596Dfe306e63AB4722A07cD = 3210676066903
0xdD49f678e116665180863F34dEBB9C9f2bda2406 = 920089440721
0x8251c0D706119F245e7e2871d0e59b64AB032FC3 = 40132210027771
0x45E6F34667f525B56EC6B0d29ab8fe23A9a533f1 = 1203957951806
0x00778a211057c47A9f8885750BBF48226771BcDC = 949042043498
0xd1051625D687b1199Db6Da2249734696CeED2433 = 354114142680
0x41D2143c3a44edd4281E8DeC9098f00E8Ad0687a = 1019799903693
0xffAF65f0f344Fc203eb7704905d7534A54e4496a = 5989573652631
0x1Fba30eC4BA8d58a39BF705E041312c4a8c152Fb = 501005136331786
0xD14b6f961FC5a5c18783976F897Bf7aDaa232018 = 23501632552
0xC5f55E124F810e2187B1ab1E30f264BF5A659eF0 = 670306398159
0x9af007D33B64E437ffEC60d0A2d28B017b6D15a2 = 10760436855036
0xa669070D106E96CC2390523E9745B425a1b3a0E0 = 301513360131
0x521b9f95E5B95C728e0f10dEE1Ad230682fe675a = 4013010182963
0x762Fa6D8615a3aB56b0753DC837E0a94677d4761 = 4120264587140
0x985147809e9C0A677e9c9BED656C984bE037D373 = 3724899525466
0x717937f7b82692e143841fe68De65b1A1EE4D3D2 = 20064807661930
0x3a4D8c1232C634255595c895e246CF16E979590e = 1204921677559
0x8E62f29678BD7756737B25FceB7Fbc9af2315541 = 53159946329868
0xa270a0FF404B0E58208BB1ba5726c50f1cD0149f = 297982775907
0x0a470975e2cc21623d660B81C43075bbbBFc5571 = 12038087308196
0x99c16D5f932CeCcFAf53143e85Ae18f03256205d = 1076638
0x87E1aD15Cd4019C883F4470839De69f98Dac38F3 = 212184958628
0x8D0a09d0B04162Dbe1eE6119247ac84903994341 = 15344920104858
0x00d4a836F92f3ABd966426af3dB116b4E7EBbc00 = 40125975167
0x5413beCcC3cC27eA5E7D07d5Fd36A0983c9996a7 = 1105864091165
0xC39fA89B072e923B73d19537044d72E502990031 = 2101417422706
0xf4dcb70Fa1205F4c4B431463D5731065A00F052b = 20062987583516
0xD10340982FAAd3B99c56A79Aa55255438F2580D4 = 23271309999897
0x5d4272799D45c325c115442e54688A416dE87094 = 20062987583516
0x0f2577cCB1e895eD1e8BFd4e709706595831e78A = 708263847943
0x5349E9F954901ceCf2D2BaaDF4b735B84b860567 = 40123046422146
0xaF7875E1062ce6CcffD42947DC16923B7A3Cb2ee = 40123046422146
0xCed2f0dcb70757339F7072A3ffA08a4A73497435 = 198220622973
0x3AE1D71738D5B936F3361006712b48415A94a9b5 = 12036329632471
0x1D54e0b28269645e75B11bAA9845D8B0c6eA4147 = 120360699695010
0x38e2bcA1635b60Ff211577Dd421Dd7671d27Eb78 = 200601166158350
0x0dCEFe8A5ed1f63B1ee63906cA91a08CE35dc38d = 67940317916374
0xF4822ba1A3F7B6Ccdf94Ac8f405056a0Fb0Ea9Ac = 28676140998724
0xf49f18FB0A2cD2aC1cE78F6db991F08E917a980d = 3007986818047
0x9073B943c749b85E83390c18cd45Df85dCd2E9Cc = 11111182524462
0xC536bF5B44A60C2094e8D6590990FF5680983f6d = 14213501290414748
0xd85351181b3F264ee0FDFa94518464d7c3DefaDa = 400997872662191
0xf47e07751a17830c49ba21525e2BE725E490B8e6 = 11278662780997
0x031Ff94207ffE04D17C6E2230700288Ecd594CC1 = 3207401159139
0x7f137Df547446CB8ccC5a378B9a80B8e5A164415 = 2004579076226
0x3Dc77A7574cAdf675264D56625D0887452bF9eA8 = 39895949520745
0xA7b10D745F3ddC8d039A39293A82705cD5915c01 = 4209591384315
0x3bc0A028c9d759c557A4157CDA31e00643a305cE = 9401579864004
0xE10BfD27a5a522f02c756816FBe0D1347919eEEd = 752762086102297
0xA3222ba5a382ccEECdA8984ffcc0d1c9fE9Af783 = 43175867980533
0x5d2e561a59B5AB7DA7ff9551502515CcDc9293d8 = 1219150179
0x1F50e977B810E35939313f5F82Bb8eD49171ec90 = 489612962339
0x89DF40061155f04a7e5c011cBE038ae9643Cb59E = 11902422679387
0xE9aDA4a27E003504cB7B86C24969320008fB8624 = 2004471377508
0xC04Bc1996320f27c0A6018cB370c9469a9Dd3a4C = 80179094463
0x7EE29Bd96a0282D161A6C9cF3646537743ad8749 = 6306662238505673
0xe18bF32c7176d7c5c13d1D807f441bE27F784e16 = 6384168747909
0x98BbE04eb8C802c4C2490526a115E33bcE85fa4b = 203531952513803
0x7D1b3c31753b2BfC51d8A03386e8Eb205F0583f4 = 4008886172979
0x0fa3b363E70B3D3288873eCB40587E63E586CC9a = 14315776718617
0xE16Ffb10d619B5C4F9A4e06711406B817E82C718 = 3136744840747
0x78F91F75C078aea847BA9d3892789Cb05d705D1d = 8097919188562
0xfFcf4d7E4779d7e3269708E18140a9322D1191bF = 10000387686237
0x91E77F9f0D3603413Fc6b2a64CeCA6d078d3d735 = 4013590661488
0xf847f17BB867F1F8Ed363A3B438fa5Ca3FA0d2A3 = 40085812810500
0x414fCEF7fa3292827a8f3195E4B31E9053e39e96 = 28945133549631
0x5e176c4698466243ec90b4ebFde7339Ec17c01f3 = 5210562827091086
0xC7cB182505deD236328e0A5AF96B1eaaBDDD303C = 2284891330199
0xc57671c8362cBe69760c07E1E030f273394dB99d = 4810029599784
0xd50E64507ba655C1EF1a62a00A482D623dA2DF2A = 3006268499864
0x695e99Bd9240701f4dCda37aec32028b6a764D83 = 1255218242062
0xfaee660F0661D847833775A36a4AC326C87426F6 = 1803731506683
0x41Cb197C82296a3F8AE84F00EAbe25D1c50ca8d5 = 4008211609240
0x68a4D45D5295035f5e235d4389056E5CC51599bE = 2004101311176
0x475159d67265842b7F5077cA3F9ef5A45035f67D = 76154063077
0x9E8237a913842D6c2352c819530324efDA097f4B = 1002027145751
0xa289364347bfC1912ab672425Abe593ec01Ca56E = 40484822281482
0x775C0529a4371c983231Ec2eD3dAE7b3CAc7e037 = 312728894368
0xd8aFbf1def44785adF4d5d58643e71Cccb67abc4 = 24865799025753
0x9bd7f4748673d9842Eb2d50dACA9a036ed06b8b9 = 1643264077844
0x10bF883DA56ECDf88be653dCE708F127AB9201bA = 1202388349642
0x4D8cd0D84E677cD2E13C29C75D7673FeD94a14Bf = 320621713159221
0xA3de285E0dD68d90856007Ba52Bc2a26D6f70B6E = 8015542828980
0x568fDD48aBC5B59BdF5dA6cd76D2DCE9A9a9aC97 = 2807933520740
0x12b3fA445A878D13E1512834032203005623b7dB = 2404644402746
0x0A15C9ee2013A4Bc16749cAd63e41bc957DfE463 = 8015481342484
0x3dFa057f36fB033bF37A8e06e43EAAa2dF07B4c5 = 20038703356211
0x5b8a8bF18F0d6e6dABCAb8d84DF44792823272d5 = 757449361593971
0x98968d051EaEea36986BeBC8360bDAAC0b618b8F = 2003870335622
0x1ab47F5B7aA83CeAf2800Bc5dF72397dcFD43030 = 220425736918324
0xf64eCD52e70b4a652BE3F41Ff4eCC775B160AB87 = 1723291501222
0x8144e639941cae7AEec9f0407F46765820607B67 = 4018548905271
0x840be98117dD83B0592C9A857614bf8e28f33d86 = 400759178409
0xa877184A3D42BF121c8182C3363427337ec49a3b = 44083832664551
0x2dC1B4DAe2851F47e60E3247cd7B3fcbF56402FA = 4501909772694
0x2Ef5A68f76999EB882e985d466Ece9a1E9daB6Ec = 120232220137267
0xe499dAA4c8dc197111542F42721609DE74aB3965 = 280530924849
0x77B8855fC7780369B62c6dD8676AfC3e6Ac41d73 = 801554282898
0xe32d9D1F1484f57F8b5198f90bcdaBC914de0B5A = 9380631906127
0xDbA31c047e795c625cE52AD248973978F7FB7400 = 12423335739123
0x9081325a86135383947B1b0f5fD0dcB105fE7d37 = 14827852334
0xEff3453d06Dd4AC4E9c02C13687485dF5f526532 = 220414021178002
0x9f109606EbCE8aBc78976bCd8f1633d8C42B4874 = 338664872026
0xaD20E117856468e6df26a39D9F96bcb676e95eC5 = 36069666041180
0x0F60DacC38f963A9aee3151750B2B38931169C82 = 120194085949857

[uni_v3_USDC_ETH]

[uni_v3_WBTC_ETH]
0x7BA605bC00eA26512a639D5e0335EAEb3e81aD94 = 34001657255015
0xD9353D77e35329BF6f609F5f8ecCc84Dda8d6C5b = 12775041842530407
0x69CB9f7cB8D09dDD82194123a96b80733b45bD21 = 57961079475893620
0xEC9881696EB62dc6eddF51Cc12B11A2C843DB076 = 2882738162445367
0x301150fe2aF68DEDFc94e0fb665435921177eFf8 = 4264294108400769
0xFD4295c1A0b07e6b706f0Ab83dC9eB461b7f17B3 = 339311838666517
0x814055779F8d2F591277b76C724b7AdC74fb82D9 = 114801164994779
0x3ace70743c1b7D7d7D8c48A3300b8b88C7DA3d58 = 47973983107959476
0x537cd8129aE8D4A3c80c1f7ddF6dD7e2f5Bda4E2 = 75677319530160461
0x8760896c309ab534294091A9Ccce689126d64A1b = 7521399716755395
0xCD662df92C282891c92a2a76396c52CC214Ce449 = 2163050669735208
0x9D28fc41FFbb91DA1f460D5C9574d4e7C5b23909 = 26654655205375083
0x43246191a2582DD9E9e20b1a411Cf5fAd901Ce0e = 10415640062444530
0xbDDd7e0d950ABd902F18068e92f61CefE58d9180 = 4186304122949661
0x98BbE04eb8C802c4C2490526a115E33bcE85fa4b = 13733689111653502
0x6F892BA322CAC139F29E50aF67975e221a994Aa0 = 21445122797819453
0x2F004586f188083fFD120a82593606AF99afbdD4 = 177565847268272405
0x41C74acBC14eB17612f1F2F17a78Ae20e5F84Ef1 = 59229343424117925
0x8eb69F50762A4d021373d206C325B7EE424C6b48 = 79589430226158462
0x1Dc7b4fB553184B6C88a0368b092aAD9b4312113 = 14639939813235089
0x39aD12b65Ed82F3D1d1FDAD844F3E411d963633f = 34720172581388855
0xb39235EBFE6BCcB274cF4d05b80Fd08Ca98BfEE4 = 19451454829056910
0x2068d776054cF1B11E9114294bd6d3554967Eb9D = 10466094207329929
0xFc1f13667C2cBC511A26e4986b535699dc9fa7e1 = 1170558091258815
0x6A07Ea36da7850cc89BE2523eB9423fBE7237061 = 1531027736026374
0xadA85B59F0fE127b81B499aFB6a73335dEF41E74 = 29353496476424106
0x523B5b2Cc58A818667C22c862930B141f85d49DD = 6673783203784681

[uni_v3_ETH_USDT]

[uni_v3_DAI_USDC]

[uni_v3_DAI_ETH]

[uni_v3_UNI_ETH]

[uni_v3_USDC_USDT]

[uni_v3_USDT_ETH_1400_2400]

[uni_v3_USDC_ETH_1400_2400]

[uni_v3_DAI_ETH_1400_2400]

[uni_v3_UST_USDT]
0x752B43999013dC6234574B1381fbcc5cC91FF5D7 = 21922662199400031
0xcd34746eAc14E60F666E3cEE9d7991D045bBf761 = 55359536632418
0xb822dce44540801363524938379977C5B155E597 = 8156109617065096
0x7d9Ae789d649b7cf5748c8b9EB96d9a2068B87Eb = 91064157183788133
0x9CBC9496aF2606446a15f85535BCCD1F7d20EAd5 = 5383067931342427
0xec630026C140a43cb98Fff7824bF8BF080007090 = 122434899428319827
0x26dc3f258767b34Cf213a60A1b2E7D1F008Cfb48 = 65712593706447762
0x1782376886155676920176b064AEa878f15cBb11 = 124298452552341
0xAFb4BCE970b77222a74D240294Bd67216114b8eB = 2410566199992405
0xA8E7bF40Cdd5F4cB4975d3E7a3214710f0045a28 = 13748586083312189
0xB0cD09cB5f6b9Eb08cA9e5D28011496F3D82BcA9 = 14536811182342456
0x79479E58fcDeECF7652ba6515bece175af77592A = 15930571557077831
0xC8158e19fC8AeB8C1Bb5a7fa3612dbF932927397 = 81051589439720666
0x0550bED1C94AFBd468aa739852632D7e9b4c2F86 = 34084008565430882
0xDC513ee74C040213C50D39e516532748E84902e6 = 68168017130861763
0xDe5b96620cB0d211645038Ca60e048b81d046Db7 = 27237083461769
0x537cd8129aE8D4A3c80c1f7ddF6dD7e2f5Bda4E2 = 123635435702469573
0x416af050BDD31eB3CF2dec83B0399b84783038B9 = 5453441370468941
0x3a14Ef4E56cf355E0D6a08a478fD43b10704535e = 995496800085599
0x14403edB6dCc966DC34e94329db4eB99BCf62d81 = 294088312261247094
0x74E9083718A13833746D7658c82A6BFb2B1Bfd50 = 1071952599245750

[uni_v3_BUSD_USDC]

[uni_v3_renBTC_wBTC]

[uni_v3_USDC_ETH_3000_4500]

[uni_v3_DAI_ETH_3000_4500]

[uni_v3_USDT_ETH_3000_4500]

[uni_v3_USDC_ETH_4200_5500]
0x7C4441BD130B51F76012cb265CcFfdC32cDC35C8 = 12541507503565093
0x99Ecc42cD0e72b13Ec43af44911aF04691671B85 = 459322995911861929
0x5Da7fa4fd38f3339aC800F74158F29F1610eD10a = 432691335051379378

[uni_v3_DAI_ETH_4200_5500]
0xce7a7f3991F6F11601D428a8772a7f9F1892be76 = 3539625816365524
0xbA3784051a7A9Cb6521E9F770750b12E96093390 = 27120630958634388
0xea32a33300D64BDdB9f09A8308D44c23616eC706 = 1130531089045299322

[uni_v3_ETH_USDT_4200_5500]
0x4A1fA61820d87261Fbb10dc65111fb60E9b557e8 = 336721533379778788
0xea32a33300D64BDdB9f09A8308D44c23616eC706 = 1340557693780518812
